### PR TITLE
Updated nix flake to allow aarch64-darwin builds as well

### PR DESCRIPTION
**Pull request by Mastermindaxe**

### CODE REVIEW

**Comment by fzakaria** [comment]
I'm not really maintaing this; happy to merge it but will be kind of blind.

I am looking for maintainers.
Let me know the confidence of the PR.

**Comment by Mastermindaxe** [comment]
I'm trying this out at work rn. I'll give you an update if this worked and will edit my PR accordingly to make it 😄

**Comment by jsoo1** [comment]
I've been using this. LGTM. Better than an unusable flake.

**Comment by fzakaria** [comment]
Merged without testing ; thank you for the contribution.
Sorry I don't have time to maintain this anymore but appreciate the PR !

**Pull request merged**
